# <center>425 Final<center>

# <center> Yihan Li 906305806<center>

In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.linear_model import LinearRegression, LogisticRegression, Lasso, Ridge, RidgeCV, LassoCV
from sklearn.metrics import mean_squared_error, accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, precision_recall_curve, auc
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier
from imblearn.over_sampling import SMOTENC
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.model_selection import LeaveOneOut
from scipy.optimize import minimize
from sklearn.cluster import KMeans
from sklearn.metrics import zero_one_loss
from sklearn.decomposition import PCA

In [26]:
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()

In [27]:
X = data.data

In [28]:
print(X)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


## (a) Standardize each feature in the data set

In [29]:
scaler = StandardScaler()
X_standardized = scaler.fit_transform(X)

In [30]:
print(X_standardized)

[[ 1.09706398 -2.07333501  1.26993369 ...  2.29607613  2.75062224
   1.93701461]
 [ 1.82982061 -0.35363241  1.68595471 ...  1.0870843  -0.24388967
   0.28118999]
 [ 1.57988811  0.45618695  1.56650313 ...  1.95500035  1.152255
   0.20139121]
 ...
 [ 0.70228425  2.0455738   0.67267578 ...  0.41406869 -1.10454895
  -0.31840916]
 [ 1.83834103  2.33645719  1.98252415 ...  2.28998549  1.91908301
   2.21963528]
 [-1.80840125  1.22179204 -1.81438851 ... -1.74506282 -0.04813821
  -0.75120669]]


## (b) Perform k-means with k = 2 on the full set of features, and on the first 2 principal components only. Compare how well the clusters found by k-means in each of these cases compare to the true targets using sklearn.metrics.zero_one_loss.

In [34]:
kmeans_full = KMeans(n_clusters=2, random_state=42).fit(X_standardized)
loss_full = zero_one_loss(data.target, kmeans_full.labels_)
n_components = 2
pca = PCA(n_components=n_components)
X_pca = pca.fit_transform(X_standardized)
kmeans_pca = KMeans(n_clusters=2, random_state=42).fit(X_pca)
loss_pca = zero_one_loss(data.target, kmeans_pca.labels_)

In [35]:
print(loss_pca)

0.09314586994727592


In [60]:
print(loss_full)

0.08787346221441128


## (c) Allocate 20% of the data to the testing set and the rest to the training set using sklearn.model_selection.train_test_split.

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X_standardized, data.target, test_size=0.2, random_state=42)

## (d) Use sklearn.linear_model.LogisticRegression to fit the logistic regression on the training set. Report the misclassification rate and the F1 score.

In [37]:
log_reg = LogisticRegression(random_state=42)
log_reg.fit(X_train, y_train)
y_pred = log_reg.predict(X_test)
misclassification_rate = 1 - accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

In [46]:
print('Misclassification_rate:',misclassification_rate)

Misclassification_rate: 0.02631578947368418


In [45]:
print('F1 score:',f1)

F1 score: 0.9790209790209791


## (e) Use sklearn.model_selection.GridSearchCV to fit a random forest of 100 trees on the training set with the maximal tree depth chosen by cross-validation over the range max_depth∈ {10, 15, 20, ... , 55, 60}. Report the misclassification rate and the F1 score.

In [55]:
param_grid = {'max_depth': list(range(10, 61, 5))}
grid_search = GridSearchCV(RandomForestClassifier(n_estimators=100, random_state=42), param_grid, cv=5)
grid_search.fit(X_train, y_train)
best = grid_search.best_estimator_
y_pred = best.predict(X_test)
misclassification_rate = 1 - accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

In [57]:
print('Misclassification_rate:',misclassification_rate)

Misclassification_rate: 0.03508771929824561


In [58]:
print('F1 score:',f1)

F1 score: 0.9722222222222222


# <center>Thanks for Reading<center>